trimscape/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from registration.views import ActivationCompleteView
from registration.views import RegistrationClosedView
from registration.views import RegistrationCompleteView
from registration.views import RegistrationView

from riskscape_registration.views import RiskscapeActivationView
from trimscape import settings

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/login/$', 'django.contrib.auth.views.login', {'template_name': 'trimscape/login.html'},
        name='login'),
    url(r'^accounts/logout/$', 'django.contrib.auth.views.logout', {'next_page': '/accounts/login'}),
    url(r'^data/$', 'patient_data.views.upload_file'),
    url(r'^data/historic/$', 'patient_data.views.upload_historic_file'),
    url(r'^$', 'analysis.views.home', name='home'),
    url(r'^(?P<outcome>[\w ]+)$', 'analysis.views.heat_map', name='outcome'),
    url(r'^map/$', 'analysis.views.heat_map', name='map'),
    url(r'^map/(?P<pk>\d+)/$', 'analysis.views.map_overlay', name='map_overlay'),
    url(r'^current/$', 'analysis.views.graph_view', {"graph_type": "current"}, name='current'),
    url(r'^current/(?P<outcome>[\w ]+)$', 'analysis.views.graph_view', {"graph_type": "current"},
        name='current-outcome'),
    url(r'^current/(?P<pk1>\d+)/(?P<pk2>-?\d+)/$', 'analysis.views.current_graph', name='current_cache'),
    url(r'^timeseries/$', 'analysis.views.graph_view', {"graph_type": "timeseries"}, name='timeseries'),
    url(r'^timeseries/(?P<outcome>[\w ]+)$', 'analysis.views.graph_view', {"graph_type": "timeseries"},
        name='timeseries-outcome'),
    url(r'^timeseries/(?P<pk1>\d+)/(?P<pk2>-?\d+)/$', 'analysis.views.timeseries_graph', name='timeseries_cache'),
    url(r'^trendline/(?P<inflection>\d+)/timeseries/(?P<pk1>\d+)/(?P<pk2>-?-?\d+)/$',
        'analysis.views.timeseries_trend', name='timeseries_trendline'),
    url(r'^about/$', 'analysis.views.about', name='about'),
    url(r'^coc/$', 'coc.views.coc_home', name='coc_home'),
    url(r'^coc/(?P<slug>[\w ]+)$', 'coc.views.coc', name='coc'),
    url(r'^coc/upload/$', 'coc.views.process_upload', name='coc-upload'),
    url(r'^django-rq/', include('django_rq.urls')),
    url(r'^registration/activate/complete/$', ActivationCompleteView.as_view(),
        name='registration_activation_complete'),
    url(r'^registration/activate/(?P<activation_key>\w+)/$',
        RiskscapeActivationView.as_view(template_name='riskscape_registration/activation_form.html'),
        name='registration_activate'),
    url(r'^registration/register/$',
        RegistrationView.as_view(template_name='riskscape_registration/registration_form.html'),
        name='registration_register'),
    url(r'^registration/register/closed/$', RegistrationClosedView.as_view(),
        name='registration_disallowed'),
    url(r'^registration/register/complete/$',
        RegistrationCompleteView.as_view(template_name='riskscape_registration/registration_complete.html'),
        name='registration_complete'),
    url(r'^registration/review/$', 'riskscape_registration.views.review', name='registration-review'),
    url(r'^registration/review/approve/(?P<pk>\d+)/$', 'riskscape_registration.views.approve', name='registration-approve'),
    url(r'^registration/review/deny/(?P<pk>\d+)/$', 'riskscape_registration.views.deny', name='registration-deny'),
    url(r'^registration/review/retry/(?P<pk>\d+)/$', 'riskscape_registration.views.retry', name='registration-retry'),
    url(r'^registration/review/delete/(?P<pk>\d+)/$', 'riskscape_registration.views.delete', name='registration-delete'),
]

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

coc/models.py
import os

from datetime import datetime
from django.core.files.storage import FileSystemStorage
from django.db import models

from patient_data import model_choices


class OverwriteStorage(FileSystemStorage):
    pass#Keep old migration happy

def path_and_rename(instance, filename):
    upload_to = 'coc'
    filename = '{}_{}-{}.json'.format(instance.coc_disease.slug, instance.site_name, datetime.now().strftime("%s"))
    return os.path.join(upload_to, filename)


class UploadCOC(models.Model):
    data_file = models.FileField(max_length=255, upload_to=path_and_rename)
    site_name = models.CharField(max_length=3, choices=model_choices.SITE_CHOICES, blank=False, null=False)
    coc_disease = models.ForeignKey('COCDisease', related_name="files", blank=False, null=False)

    def __str__(self):
        return "{}:{}".format(self.get_site_name_display(), self.coc_disease.name)

    def save(self, *args, **kwargs):
        UploadCOC.objects.filter(site_name=self.site_name, coc_disease=self.coc_disease).delete()
        super(UploadCOC, self).save(*args, **kwargs)

    class Meta:
        ordering = ['site_name']


class COCDisease(models.Model):
    name = models.CharField(max_length=50)
    slug = models.CharField(max_length=5, primary_key=True)

    def __str__(self):
        return self.name

coc/forms.py
import arrow
from django import forms

from coc.models import UploadCOC


class UploadCOCForm(forms.ModelForm):
    class Meta:
        model = UploadCOC
        fields = ['data_file', 'site_name', 'coc_disease']


def get_year_choices(choices):
    return choices + [(str(y + 1), str(y + 1)) for y in range(2009, arrow.now().year)]


def get_site_choices(choices, disease):
    return choices + [(s.site_name, s.get_site_name_display()) for s in UploadCOC.objects.filter(coc_disease=disease)]


class COCForm(forms.Form):
    ATTRS = {'class': 'custom-select form-control small'}
    site = forms.ChoiceField(label='Site',
                             choices=(('x', 'All'),),
                             widget=forms.Select(attrs=ATTRS))
    year = forms.ChoiceField(label='Year', choices=(('YEAR', 'All'),),
                             widget=forms.Select(attrs=ATTRS))
    age_group = forms.ChoiceField(label='Age Group',
                                  choices=(('x', 'All'), ('1', '0-19'), ('2', '20-39'), ('3', '40-59'), ('4', '59+'),
                                           ('5', 'Unknown')),
                                  widget=forms.Select(attrs=ATTRS))
    birth_cohort = forms.ChoiceField(label='Birth Cohort',
                                     choices=(('x', 'All'), ('1', 'Before 1945'), ('2', '1945 to 1965'),
                                              ('3', 'After 1965'), ('4', 'Unknown')),
                                     widget=forms.Select(attrs=ATTRS))
    sex = forms.ChoiceField(label="Sex", choices=(('x', 'All'), ('1', 'Female'), ('2', 'Male'), ('3', 'Unknown')),
                            widget=forms.Select(attrs=ATTRS))
    race_ethnicity = forms.ChoiceField(label="Race/Ethnicity",
                                       choices=(('x', 'All'), ('1', 'Asian'), ('2', 'Black'), ('3', 'Caucasian'),
                                                ('4', 'Hispanic'), ('5', 'Other'), ('6', 'Unknown')),
                                       widget=forms.Select(attrs=ATTRS))

    def __init__(self, disease_slug, *args, **kwargs):
        super(COCForm, self).__init__(*args, **kwargs)
        self.fields['year'].choices = get_year_choices(self.fields['year'].choices)
        self.fields['site'].choices = get_site_choices(self.fields['site'].choices, disease_slug)

coc/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt

from coc.forms import COCForm, UploadCOCForm
from coc.models import UploadCOC, COCDisease
from trimscape import utils


@login_required
def coc_home(request):
    data = []
    for d in COCDisease.objects.all():
        data.append(
            {"display_name": d.name, "name": d.slug, "files": ",".join([f.data_file.url for f in d.files.all()])})

    return render(request, 'coc/home.html',
                  {"coc": True, "outcomes": utils.nest(utils.pad_dashboard(data)),
                   "sites": UploadCOC.objects.filter(coc_disease='hepc')})


@login_required
def coc(request, slug):
    form = COCForm(slug)
    return render(request, 'coc/detail.html',
                  {"coc": True, "form": form, "sites": UploadCOC.objects.filter(coc_disease=slug)})


@csrf_exempt
def process_upload(request):
    if request.method == 'POST':
        form = UploadCOCForm(request.POST, request.FILES)
        if form.is_valid():
            upload_data = form.save()
            return HttpResponse('Upload Successful')
        else:
            return HttpResponse("Errors %s" % form.errors)
    else:
        return HttpResponse(status=403)

coc/templates/coc/dashboard-body.html
{% if outcome.files|length == 0 %}
    <div class="col-md-12">
        Disease not available
    </div>
{% else %}
    <div id="{{ outcome.name }}-container" class="coc-dash"
         class="col-md-12" data-filenames="{{ outcome.files }}" data-url='{% url 'coc' outcome.name %}'>
        Disease good
    </div>
{% endif %}

coc/templates/coc/detail.html
{% extends 'trimscape/app_base.html' %}
{% load staticfiles %}

{% block main %}
    <ol class="breadcrumb bg-faded">
        <form id="table-form">
            <div class="row">
                {% for field in form %}
                    <div class="col-md-2 form-group {% if not field.name == 'site' %}invisible{% endif %}">
                    {{ field.invisible }}
                        <label class="small" for="{{ field.id_for_label }}">{{ field.label }}</label>
                        {{ field }}
                    </div>
                {% endfor %}
            </div>
        </form>
        <button class="btn btn-sm btn-primary" onclick="updateTable();">Update Table and Graph</button>
        <button class="btn btn-sm btn-secondary" onclick="resetForm();">Reset</button>
        <button id="toggle-inline-graph" class="btn btn-sm btn-info pull-xs-right">Show Inline Graph</button>
    </ol>
    <div class="row">
        <div class="col-md-12">
            <table id="coc-table" class="table table-hover table-sm">
                <thead>
                <tr>
                    <th>{{ sites.0.coc_disease }}</th>
                    <th>Count</th>
                    <th>Percent</th>
                </tr>
                </thead>
                <tbody class="tr-click">
                </tbody>
            </table>
            <div class="card card-outline-primary">
                <div class="card-header bg-primary text-white">Click Row to Add to Graph
                    <button class="btn btn-sm btn-primary pull-xs-right" onclick="resetGraph();">Reset</button>
                </div>
                <div class="card-block">
                    <div class="card-body">
                        <div id="coc-chart"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block script %}
    {{ block.super }}
    <script type='text/javascript' src="{% static "trimscape/js/d3-3.5.17.min.js" %}"></script>
    <script type='text/javascript' src="{% static "trimscape/js/c3-0.4.11.min.js" %}"></script>
    <script type='text/javascript'>
        var siteData = {};
        var rowMetaData = null;
        let activeColors = [];
        let filters = null;

        let chart = c3.generate({
            bindto: '#coc-chart',
            data: {
                type: 'bar',
                columns: [],
                color: function (color, d) {
                    try {
                        return activeColors[d.index];
                    } catch (err) {
                        return '#0275D8';
                    }
                },
                line: {
                    connectNull: true
                },
            },
            bar: {
                zerobased: true
            },
            axis: {
                x: {
                    type: 'category',
                    tick: {}
                },
                y: {
                    padding: {top: 0, bottom: 0},
                    default: [0, 1],
                    max: 1,
                    min: 0,
                    tick: {
                        values: [0, .1, .20, .30, .40, .50, .60, .70, .80, .90, 1],
                        format: d3.format(".0%")
                    }

                }
            },
            tooltip: {
                format: {
                    value: function (value, ratio, id, index) {
                        var format = d3.format('.2%');
                        let count = $($('tr[data-graphed=true]').get(index)).find('td:nth(1)').html();
                        let actual = " (" + count + "/" + maxVal + ")";
                        return format(value) + actual;
                    }
                }
            },
            legend: {
                show: false
            },
            transition: {
                duration: 500
            },
            size: {height: 300}
        });

        {% for site in sites %}
            siteData['{{ site.site_name }}'] = null;
        {% endfor %}

        $("#toggle-inline-graph").on('click', function () {
            updateInlineGraph($(this), $(this).html().includes("Show"));
        });

        $('#coc-table').on('click', 'td', function () {
            let tr = $(this).parent();
            let graphed = tr.attr("data-graphed") == "true";
            if (graphed) {
                degraphRow(tr);
            } else {
                let color = colors[$('tbody tr').index(tr) % colors.length];
                tr.find('td').css({'border-bottom': '2px solid ' + color});
                tr.attr("data-graphed", true);
            }
            updateGraph();
        });

        $('#coc-table').on('mouseenter', 'tr', function(){
            let nest = parseInt($(this).attr('data-nest'))-1;
            if (nest >= 0) {
                $(this).addClass('denominator').find("span.tag").html("Numerator");
                $(this).prevAll('[data-nest="' + nest + '"]:first').addClass('denominator').find("span.tag").html("Denominator");
            }
        });

        $('#coc-table').on('mouseleave', 'tr', function(){
            $('.denominator').removeClass('denominator');
            $('span.tag').html("");
        });
        function degraphRow(row) {
            row.find('td').css({'border-bottom': ''});
            row.attr("data-graphed", false);
        }
        function resetGraph() {
            $('tr[data-graphed]').each(function () {
                degraphRow($(this));
            });
            updateGraph();
        }

        let maxVal = 0;
        function updateGraph() {
            maxVal = 0;
            let graphVals = [];
            let cats = [];
            activeColors = [];
            $('tbody tr').each(function (idx) {
                if ($(this).attr('data-graphed') == 'true') {
                    let count = parseInt($(this).find('td:eq(1)').html());
                    cats.push($(this).find('td:eq(0)').text().replace("Numerator",""));
                    maxVal = Math.max(maxVal, count);
                    graphVals.push(count);
                    activeColors.push(colors[idx % colors.length]);
                }
            });

            if (graphVals.length > 0) {
                let graphPercent = [];
                graphPercent.push("");
                graphVals.forEach(function (e) {
                    graphPercent.push(e / maxVal * 1.0);
                });
                chart.load({columns: [graphPercent], categories: cats});
            } else {
                chart.unload({ids: [""]});
            }
        }

        function getSiteData(site, url) {
            return $.getJSON(url).done(function (data) {
                siteData[site] = data['rowdata'];
                rowMetaData = data['rowmeta'];
                filters = data['filters'];
            });
        }

        function loadData() {
            activateLoadingOverlay();
            var deferred = [];
            {% for site in sites %}
                deferred.push(getSiteData('{{ site.site_name }}', '{{ site.data_file.url }}?{{ site.pk }}'));
            {% endfor %}

            $.when.apply($, deferred).done(function () {
                updateSelectors();
                setRows();
                updateTable();
                deactivateLoadingOverlay();
            });
        }

        function updateSelectors(){
            $.each(filters, function(idx, val){
                let goodFilter = val;
                $("select[id='id_"+goodFilter+"']").parents("div").removeClass("invisible");
            });
            $("select").parents("div.invisible").remove();
        }

        function updateInlineGraph(el, show) {
            $('td:first-child').each(function () {
                let size = '0% 100%';
                if (show) {
                    size = $(this).siblings(":last").html() + ' 100%';
                }
                $(this).css('background-size', size);
            });
            if (show) {
                el.html(el.html().replace('Show', 'Hide'));
            } else {
                el.html(el.html().replace('Hide', 'Show'));
            }
        }

        function setRows() {
            let colorIdx = 0;
            let colorList = [];
            for (var k in rowMetaData) {
                var rmd = rowMetaData[k];
                let nest = parseInt(rmd["nest"]);
                var tr = $('<tr>').attr({"id": "row-" + k, "data-graphed": false, "data-nest": nest});
                let tdCSS = {};
                if (nest == 0) {
                    tr.addClass('font-weight-bold');
                } else {
                    tdCSS['background-position'] = (rmd['nest'] * 20) - 5 + 'px';
                }

                if (nest == colorList.length) {
                    colorList.push(colors[colorIdx++]);
                } else if (nest < colorList.length) {
                    colorList = colorList.splice(0, nest + 1);
                }
                let barColor = hexToRGB(colorList[nest], 50);
                tdCSS['padding-left'] = rmd['nest'] * 20 + 'px';
                tdCSS['background-size'] = '0% 100%';
                tdCSS['background-repeat'] = 'no-repeat';
                tdCSS['background-image'] = 'linear-gradient(' + barColor + ',' + barColor + ')';
                tdCSS['border-right'] = '1px solid lightgray';
                tdCSS['transition'] = 'background-size 0.5s';

                tr.append(($('<td>')
                    .css(tdCSS)
                    .html(rmd['name']))
                    .prepend($("<i>").addClass("fa fa-arrow-circle-right text-primary"))
                    .append($("<i>").addClass("fa fa-info-circle")
                        .attr({"data-toggle": "tooltip", "data-placement": "top", "title": rmd['description']}))
                    .append($("<span>").addClass("tag tag-pill tag-primary pull-right"))
                )
                    .append($('<td>'))
                    .append($('<td>'));
                $('#coc-table tbody').append(tr);
            }
            $('[data-toggle="tooltip"]').tooltip();
        }

        function showData(site, key) {
            var data = mergeData(site, key);
            if (data == null) {
                $('#error-alert').show();
                resetTable();
            } else {
                $('#error-alert').hide();

                for (var k in data) {
                    var datum = data[k];
                    if (datum == null) {
                        datum = '-';
                        var percent = '-';
                    } else {
                        percent = datum / data[rowMetaData[k]['pcalc']];
                        if (isNaN(percent) || percent == Infinity) {
                            percent = "-";
                        }
                        else {
                            percent = percent * 100;
                            if (percent < 100 && percent > 0) {
                                percent = percent.toFixed(1);
                            }
                            percent += "%";
                        }
                    }
                    $('tr#row-' + k + " td:eq(1)").html(datum);
                    $('tr#row-' + k + " td:last").html(percent);
                }
            }
            updateInlineGraph($("#toggle-inline-graph"), !$('#toggle-inline-graph').html().includes('Show'));
        }

        function resetTable() {
            $('tbody tr td').not(":first-child").html("-");
        }

        function mergeData(site, key) {
            if (site != 'x') {
                return siteData[site][key];
            } else {
                var data = null;
                var siteKeys = Object.keys(siteData);
                for (var i = 0; i < siteKeys.length; i++) {
                    var sd;
                    try {
                        sd = siteData[siteKeys[i]][key];
                    } catch (e) {
                    }
                    if (typeof sd != 'undefined') {
                        if (data == null) {
                            data = $.extend({}, sd);
                        } else {
                            for (var field in data) {
                                if (data[field] != null && sd[field] != null) {
                                    data[field] += sd[field]
                                }
                            }
                        }
                    }
                }
                return data;
            }
        }

        function updateTable() {
            var site = $('select#id_site').val();
            var key = '';
            $('#table-form select:not(#id_site)').each(function () {
                key += $(this).val();
            });
            showData(site, key);
            updateGraph();
        }

        function resetForm() {
            $('select').each(function () {
                $(this).val($(this).find('option:first').val());
            });
            updateTable();
        }
        loadData();
    </script>
{% endblock %}

coc/templates/coc/home.html
{% extends 'trimscape/app_base.html' %}
{% load staticfiles %}

{% block main %}
    <div class="row">
        <div>
            {% include 'trimscape/dashboard.html' with body="coc/dashboard-body.html" %}
        </div>
    </div>
{% endblock %}
{% block script %}
    {{ block.super }}
    <script type='text/javascript' src="{% static "trimscape/js/d3-3.5.17.min.js" %}"></script>
    <script type='text/javascript' src="{% static "trimscape/js/c3-0.4.11.min.js" %}"></script>
    <script type='text/javascript'>

        function getSiteData(target, url) {
            return $.getJSON(url).done(function (data) {
                let disease = diseasedata[target.attr("id")];
                disease['data'].push(data['rowdata']);
                disease['meta'] = data['rowmeta'];
                disease['filters'] = data['filters'];
            });
        }

        let diseasedata = {};

        function loadData() {
            activateLoadingOverlay();
            $(".coc-dash").each(function () {
                let filenames = $(this).data("filenames");
                let deferred = [];
                if (filenames) {
                    setClickableCard($(this));
                    diseasedata[$(this).attr("id")] = {'meta': null, 'data': [], 'filters': null};
                    filenames = filenames.split(",");
                    for (let i = 0; i < filenames.length; i++) {
                        deferred.push(getSiteData($(this), filenames[i]));
                    }

                }
                $.when.apply($, deferred).done(function () {
                    $(".coc-dash").each(function () {
                        let id = $(this).attr("id");
                        if (diseasedata[id]['meta']) {
                            loadChart($(this), diseasedata[id]['meta'], diseasedata[id]['data'], diseasedata[id]['filters']);
                        }
                    });
                    deactivateLoadingOverlay();
                });
            });
        }

        function setClickableCard(target){
            let card = target.parents(".card");
            card.addClass("dash-target");
            card.on('click', function(){
                window.location.href=target.data('url');
            })
        }

        function loadChart(target, meta, data, filters) {
            let percentages = calculatePercent(meta, mergeData(meta, data, getBaseDataKey(filters)));
            percentages.unshift("data");
            var width = parseInt(target.css('width').replace("px",""));

            let chart = c3.generate({
                bindto: "#"+target.attr("id"),
                data: {
                    type: 'bar',
                    columns: [percentages],
                    line: {
                        connectNull: true
                    },
                },
                color: {pattern: ['#fff']},
                axis: {
                    x: {show: false},
                    y: {show: false}
                },
                bar: {
                    zerobased: true
                },
                legend: {
                    show: false
                },
                tooltip: {
                    show: false
                },
                interaction: {
                    enabled: false
                },
                size: {height: 150, width: width}
            });

        }

        function getBaseDataKey(filters){
            if ($.inArray('year',filters)>-1){
                return 'YEAR'+Array(filters.length).join('x');
            }else{
                return Array(filters.length+1).join('x');
            }
        }

        function calculatePercent(meta, data) {
            let perc = [];
            for (var k in data) {
                var datum = data[k];
                if (datum == null) {
                    var percent = null;
                } else {
                    percent = datum / data[meta[k]['pcalc']];
                    if (isNaN(percent) || percent == Infinity) {
                        percent = null;
                    }
                    else {
                        percent = percent * 100;
                        if (percent < 100 && percent > 0) {
                            percent = parseFloat(percent.toFixed(1));
                        }
                    }
                    perc.push(percent)
                }
            }
            return perc;
        }

        function mergeData(meta, sites, key) {
            var data = null;
            var siteKeys = Object.keys(meta);
            for (var j = 0; j < sites.length; j++) {
                for (var i = 0; i < siteKeys.length; i++) {
                    var sd;
                    try {
                        sd = sites[j][key];
                    } catch (e) {
                        console.log(e);
                    }
                    if (typeof sd != 'undefined') {
                        if (data == null) {
                            data = $.extend({}, sd);
                        } else {
                            for (var field in data) {
                                if (data[field] != null && sd[field] != null) {
                                    data[field] += sd[field]
                                }
                            }
                        }
                    }
                }
            }
            return data;
        }

        loadData();
    </script>
{% endblock %}